### ISSUE TITLE
Crash With Forge 2064

### ISSUE THREAD

**Issue by Hastling** [Belgabor/DrawersBits#3] opened 2016-08-15 19:41 UTC
The crash occurs on start up before you get to the main menu.

http://pastebin.com/YiB3gupi

**Comment by UnNinja** [comment] 2016-08-15 21:40
Experiencing the same issue with forges 2061 http://pastebin.com/e2YRxxsS and 2053 http://pastebin.com/pZxqcq4C

**Comment by kreezxil** [comment] 2016-08-16 00:13
Confirmed also with Forge 2065

Issue:  bitdrawers{0.21} crashes dedicated Forge 1.10.2 build 2065 on startup

crash report:
https://gist.github.com/feee8c11b2635729fd85f438a7c2993f

fml server latest:
https://gist.github.com/68931b1ae6b9390b4ecd3059892a0588

**Comment by MokahTGS** [comment] 2016-08-16 02:23
Confirmed with my setup:

http://pastebin.com/mZ6txpra

**Comment by Belgabor** [comment] 2016-08-16 03:06
```
StorageDrawers{1.10.2-3.2.4}
```

Version 0.21 only works with version 3.2.2, in fact I'm surprised Minecraft loads without giving you a version error (it's supposed to).

**Comment by Belgabor** [comment] 2016-08-16 03:13
Just verified, works with StorageDrawers-3.2.2 and Chameleon-2.1.6 on Forge 2065. I'll close this because it's technically not a bug with the correct versions. I will be working on an update for the current version of Storage Drawers of course.

**Closed as completed by Belgabor** 2016-08-16 03:13 UTC
